/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author HP
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jBtnlogout = new javax.swing.JButton();
        jBtnFinance = new javax.swing.JButton();
        jBtnReport = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnAddUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setMinimumSize(new java.awt.Dimension(669, 411));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(669, 411));
        jPanel1.setPreferredSize(new java.awt.Dimension(669, 411));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnlogout.setBackground(new java.awt.Color(0, 0, 0));
        jBtnlogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnlogout.setForeground(new java.awt.Color(102, 204, 255));
        jBtnlogout.setText("Logout");
        jBtnlogout.setBorder(null);
        jBtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 140, 40));

        jBtnFinance.setBackground(new java.awt.Color(0, 51, 51));
        jBtnFinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/money.png"))); // NOI18N
        jBtnFinance.setBorder(null);
        jBtnFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinanceActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnFinance, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, 150));

        jBtnReport.setBackground(new java.awt.Color(0, 51, 51));
        jBtnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/document.png"))); // NOI18N
        jBtnReport.setBorder(null);
        jBtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReportActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, 150));

        jBtnDel.setBackground(new java.awt.Color(0, 51, 51));
        jBtnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/shopping-cart.png"))); // NOI18N
        jBtnDel.setBorder(null);
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 150));

        jBtnAddUpdate.setBackground(new java.awt.Color(0, 51, 51));
        jBtnAddUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\add-to-cart.png")); // NOI18N
        jBtnAddUpdate.setAlignmentY(0.0F);
        jBtnAddUpdate.setBorder(null);
        jBtnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAddUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("ADD & UPDATE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("DASHBOARD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("ITEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DELETE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ITEM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FINANCE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REPORT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/blackbg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 650, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddUpdateActionPerformed
item j1=new item();
j1.show();

dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnAddUpdateActionPerformed

    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
      delete j2=new delete();
j2.show();

dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDelActionPerformed

    private void jBtnFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinanceActionPerformed
      Bill j3=new Bill();
j3.show();

dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFinanceActionPerformed

    private void jBtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReportActionPerformed
      Report j4=new Report();
j4.show();

dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnReportActionPerformed

    private void jBtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnlogoutActionPerformed
        logininterface log=new logininterface();
log.show();

dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jBtnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAddUpdate;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnFinance;
    private javax.swing.JButton jBtnReport;
    private javax.swing.JButton jBtnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
