/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class item extends javax.swing.JFrame {

    /**
     * Creates new form item
     */
    public item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextItemNo = new javax.swing.JTextField();
        jTextItemname = new javax.swing.JTextField();
        jTextUnitprice = new javax.swing.JTextField();
        jTextQuantity = new javax.swing.JTextField();
        jDateexpire = new com.toedter.calendar.JDateChooser();
        jDatereceive = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddup = new javax.swing.JTable();
        jButtonback = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtondel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(669, 411));
        setPreferredSize(new java.awt.Dimension(669, 411));

        bg.setBackground(new java.awt.Color(0, 102, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("ADD & UPDATE ITEM");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Item No");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Expire Date");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Item Name");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Receive Date");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("unit Price");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Quantity");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jTextItemNo.setBackground(new java.awt.Color(0, 0, 0));
        jTextItemNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextItemNo.setForeground(new java.awt.Color(0, 204, 204));
        bg.add(jTextItemNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));

        jTextItemname.setBackground(new java.awt.Color(0, 0, 0));
        jTextItemname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextItemname.setForeground(new java.awt.Color(0, 204, 204));
        jTextItemname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextItemnameKeyPressed(evt);
            }
        });
        bg.add(jTextItemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        jTextUnitprice.setBackground(new java.awt.Color(0, 0, 0));
        jTextUnitprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextUnitprice.setForeground(new java.awt.Color(0, 204, 204));
        bg.add(jTextUnitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));

        jTextQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jTextQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextQuantity.setForeground(new java.awt.Color(0, 204, 204));
        bg.add(jTextQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        jDateexpire.setBackground(new java.awt.Color(0, 0, 0));
        jDateexpire.setForeground(new java.awt.Color(0, 204, 204));
        bg.add(jDateexpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, -1));

        jDatereceive.setBackground(new java.awt.Color(0, 0, 0));
        jDatereceive.setForeground(new java.awt.Color(0, 204, 204));
        bg.add(jDatereceive, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 120, -1));

        jTableAddup.setBackground(new java.awt.Color(0, 102, 102));
        jTableAddup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAddup.setForeground(new java.awt.Color(0, 204, 204));
        jTableAddup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNo", "ItemName", "ReceiveDate", "ExpireDate", "UnitPrice", "Quantity"
            }
        ));
        jTableAddup.setShowGrid(true);
        jScrollPane1.setViewportView(jTableAddup);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 590, 100));

        jButtonback.setBackground(new java.awt.Color(0, 0, 0));
        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(0, 204, 204));
        jButtonback.setText("Back");
        jButtonback.setBorder(null);
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });
        bg.add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 80, 30));

        jButtonadd.setBackground(new java.awt.Color(0, 0, 0));
        jButtonadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonadd.setForeground(new java.awt.Color(0, 204, 204));
        jButtonadd.setText("Add");
        jButtonadd.setBorder(null);
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });
        bg.add(jButtonadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 90, 30));

        jButtonupdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonupdate.setForeground(new java.awt.Color(0, 204, 204));
        jButtonupdate.setText("Update");
        jButtonupdate.setBorder(null);
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });
        bg.add(jButtonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, 30));

        jButtonclear.setBackground(new java.awt.Color(0, 0, 0));
        jButtonclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonclear.setForeground(new java.awt.Color(0, 204, 204));
        jButtonclear.setText("Clear");
        jButtonclear.setBorder(null);
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });
        bg.add(jButtonclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 90, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/blackbg.jpg"))); // NOI18N
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 650, 160));

        jButtondel.setBackground(new java.awt.Color(0, 0, 0));
        jButtondel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtondel.setForeground(new java.awt.Color(0, 204, 204));
        jButtondel.setText("Delete");
        jButtondel.setBorder(null);
        jButtondel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondelActionPerformed(evt);
            }
        });
        bg.add(jButtondel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
      dashboard ds=new dashboard();
ds.show();

dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
   
        SimpleDateFormat dFormat = new SimpleDateFormat();
        
if(jTextItemNo.getText().equals("")||jTextItemname.getText().equals("")||jTextUnitprice.getText().equals("")||
        jTextQuantity.getText().equals("")||jDatereceive.getDate()==null||jDateexpire.getDate()==null) 
{
JOptionPane.showMessageDialog(this,"Please Enter All Data");
}
else
{
String data[]={jTextItemNo.getText(),jTextItemname.getText(),dFormat.format(jDatereceive.getDate()),
    dFormat.format(jDateexpire.getDate()),jTextUnitprice.getText(),jTextQuantity.getText(),
   };

DefaultTableModel tblModel = (DefaultTableModel)jTableAddup.getModel();
tblModel.addRow(data);
JOptionPane.showMessageDialog(this,"Add Successfully");

}

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jTextItemnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextItemnameKeyPressed
     char c = evt.getKeyChar();
if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
{
jTextItemname.setEditable(true);
}  
else
{
jTextItemname.setEditable(false);
}    // TODO add your handling code here:
    }//GEN-LAST:event_jTextItemnameKeyPressed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
       
        DefaultTableModel tblModel = (DefaultTableModel)jTableAddup.getModel();
        
        
     String itemno =jTextItemNo.getText();
     String itemname =jTextItemname.getText();
     SimpleDateFormat dFormat=new SimpleDateFormat();
     String receivedate = dFormat.format(jDatereceive.getDate());
     String expiredate = dFormat.format(jDateexpire.getDate());
     String price = jTextUnitprice.getText();
     String Quantity =  jTextQuantity.getText();
    
     tblModel.setValueAt(itemno,jTableAddup.getSelectedRow(), 0);
     tblModel.setValueAt( itemname, jTableAddup.getSelectedRow(), 1);
     tblModel.setValueAt(receivedate, jTableAddup.getSelectedRow(), 2);
     tblModel.setValueAt(expiredate, jTableAddup.getSelectedRow(), 3);
     tblModel.setValueAt(price, jTableAddup.getSelectedRow(), 4);
     tblModel.setValueAt(Quantity, jTableAddup.getSelectedRow(), 5);
        
        
       
     if(jTableAddup.getSelectedRowCount() == 1){
            JOptionPane.showMessageDialog(this,"Update Successfully");
    
       }  
     else{
            if(jTableAddup.getSelectedRowCount() == 0){
     
            JOptionPane.showMessageDialog(this,"table is empty");
            }else 
            {
     
            JOptionPane.showMessageDialog(this,"please select single row for update");
             }
     
         }
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButtondelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondelActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTableAddup.getModel();
 if(jTableAddup.getSelectedRowCount() == 1){
            tblModel.removeRow(jTableAddup.getSelectedRow());
    
       }  
     else{
            if(jTableAddup.getSelectedRowCount() == 0){
     
            JOptionPane.showMessageDialog(this,"table is empty");
            }else{
     
            JOptionPane.showMessageDialog(this,"please select single row for update");
             }
     
         }

// TODO add your handling code here:
    }//GEN-LAST:event_jButtondelActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
        
       ;
         jTextItemNo.setText("");
         jTextItemname.setText("");       
         jTextQuantity.setText("");
         jTextUnitprice.setText("");
    }//GEN-LAST:event_jButtonclearActionPerformed

    /**
     * @param args the command line arguments
     */
   
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondel;
    private javax.swing.JButton jButtonupdate;
    private com.toedter.calendar.JDateChooser jDateexpire;
    private com.toedter.calendar.JDateChooser jDatereceive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAddup;
    private javax.swing.JTextField jTextItemNo;
    private javax.swing.JTextField jTextItemname;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextUnitprice;
    // End of variables declaration//GEN-END:variables
}
