/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class loging extends javax.swing.JFrame {

    /**
     * Creates new form loging
     */
    public loging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        bgimage = new javax.swing.JLabel();
        appname = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadinglbl = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        setMaximumSize(new java.awt.Dimension(761, 455));
        setMinimumSize(new java.awt.Dimension(761, 455));
        setUndecorated(true);

        bgpanel.setBackground(new java.awt.Color(0, 102, 102));
        bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/supermarket.png"))); // NOI18N
        bgpanel.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 64, 543, 350));

        appname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        appname.setForeground(new java.awt.Color(255, 255, 255));
        appname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appname.setText("EXPRESS MINI MART");
        bgpanel.add(appname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 450, 50));

        jProgressBar1.setBackground(new java.awt.Color(0, 204, 204));
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 204));
        bgpanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 760, -1));

        loadinglbl.setForeground(new java.awt.Color(255, 255, 255));
        loadinglbl.setText("loading...");
        bgpanel.add(loadinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        percentage.setForeground(new java.awt.Color(255, 255, 255));
        percentage.setText("0 %");
        bgpanel.add(percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        loging lg=new loging();
        lg.setVisible(true);
        
        try{
            for(int i=0;i<=100;i++){
            Thread.sleep(100);
        lg.percentage.setText(i+ " %");
        
        if(i==10){
            lg.loadinglbl.setText("Turning on Module......");
            }
           if(i==20){
            lg.loadinglbl.setText("Loading on Module......");
            } 
            if(i==50){
            lg.loadinglbl.setText("Connecting to Database......");
            }
            if(i==70){
            lg.loadinglbl.setText("Connection Successful......");
            }
            if(i==80){
            lg.loadinglbl.setText("Launching Application......");
            }
            lg.jProgressBar1.setValue(i);
            
            }
       
            
    }catch(Exception e)
    {
      JOptionPane.showMessageDialog(null, e);
    }
     logininterface log=new logininterface();
    lg.setVisible(false);
   log.setVisible(true);
    
    lg.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appname;
    private javax.swing.JLabel bgimage;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loadinglbl;
    private javax.swing.JLabel percentage;
    // End of variables declaration//GEN-END:variables
}
