/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;


import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class logininterface extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public logininterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanelog = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        themesen = new javax.swing.JLabel();
        lockicon = new javax.swing.JLabel();
        keyicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnsignup = new javax.swing.JButton();
        btnfrgtpwd = new javax.swing.JButton();
        txtlogPswrd = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        pwdlbl = new javax.swing.JLabel();
        loginlbl = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        shopicon = new javax.swing.JLabel();
        ontopblue = new javax.swing.JLabel();
        behindblue = new javax.swing.JLabel();
        blkwood = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setMinimumSize(new java.awt.Dimension(669, 411));
        setSize(new java.awt.Dimension(669, 411));

        bgpanelog.setBackground(new java.awt.Color(0, 102, 102));
        bgpanelog.setMinimumSize(new java.awt.Dimension(761, 455));
        bgpanelog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnexit.setBackground(new java.awt.Color(0, 0, 51));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(153, 153, 255));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logout.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.setOpaque(false);
        bgpanelog.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        themesen.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        themesen.setForeground(new java.awt.Color(255, 255, 255));
        themesen.setText("On your way home");
        bgpanelog.add(themesen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 70));

        lockicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lockicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/lock (1).png"))); // NOI18N
        bgpanelog.add(lockicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, 30));

        keyicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/key (2).png"))); // NOI18N
        bgpanelog.add(keyicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 20, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXPRESS MINI MART");
        bgpanelog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnlogin.setBackground(new java.awt.Color(0, 0, 51));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(153, 153, 255));
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/login.png"))); // NOI18N
        btnlogin.setText("Login");
        btnlogin.setOpaque(false);
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        bgpanelog.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 255));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        bgpanelog.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 160, 30));

        btnsignup.setBackground(new java.awt.Color(0, 0, 51));
        btnsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(153, 153, 255));
        btnsignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/user.png"))); // NOI18N
        btnsignup.setText("Signup");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        bgpanelog.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        btnfrgtpwd.setBackground(new java.awt.Color(0, 0, 51));
        btnfrgtpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfrgtpwd.setForeground(new java.awt.Color(153, 153, 255));
        btnfrgtpwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/lock (2).png"))); // NOI18N
        btnfrgtpwd.setText("Forgot Password");
        btnfrgtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrgtpwdActionPerformed(evt);
            }
        });
        bgpanelog.add(btnfrgtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txtlogPswrd.setBackground(new java.awt.Color(0, 0, 0));
        txtlogPswrd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtlogPswrd.setForeground(new java.awt.Color(204, 204, 255));
        txtlogPswrd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlogPswrd.setBorder(null);
        txtlogPswrd.setOpaque(false);
        bgpanelog.add(txtlogPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 160, 30));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));
        bgpanelog.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 180, 10));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        bgpanelog.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 170, 10));

        pwdlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pwdlbl.setForeground(new java.awt.Color(204, 204, 255));
        pwdlbl.setText("Password");
        bgpanelog.add(pwdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        loginlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginlbl.setForeground(new java.awt.Color(204, 204, 255));
        loginlbl.setText("LOGIN");
        bgpanelog.add(loginlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 255));
        username.setText("Username");
        bgpanelog.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        shopicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/shop.png"))); // NOI18N
        bgpanelog.add(shopicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, 130));

        ontopblue.setBackground(new java.awt.Color(0, 102, 153));
        ontopblue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ontopblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/pngaaa.com-243515.png"))); // NOI18N
        bgpanelog.add(ontopblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 350));

        behindblue.setBackground(new java.awt.Color(0, 102, 153));
        behindblue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        behindblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/pngaaa.com-243515.png"))); // NOI18N
        bgpanelog.add(behindblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 270, 340));

        blkwood.setBackground(new java.awt.Color(0, 102, 153));
        blkwood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blkwood.setForeground(new java.awt.Color(204, 204, 255));
        blkwood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blkwood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/blackbg.jpg"))); // NOI18N
        blkwood.setLabelFor(ontopblue);
        blkwood.setText("Username");
        bgpanelog.add(blkwood, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 350, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgpanelog, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanelog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        String user=txtUsername.getText();
        String password=txtlogPswrd.getText();
        
        //login validation
        if(user.equals("")&&password.equals(""))
                {
                JOptionPane.showMessageDialog(this, "You should Enter Username and Password");
                }
        else if(!(user.equals(""))&&password.equals(""))
                {
                JOptionPane.showMessageDialog(this, "You should Enter Password..");
                }
            else if(!(password.equals(""))&&user.equals(""))
                {
                JOptionPane.showMessageDialog(this, "You should Enter Username..");
                }
    }//GEN-LAST:event_btnloginMouseClicked

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
         signup si=new signup ();
si.show();

dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnfrgtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrgtpwdActionPerformed
         frgotpwd g=new  frgotpwd();
g.show();

dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnfrgtpwdActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logininterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel behindblue;
    private javax.swing.JPanel bgpanelog;
    private javax.swing.JLabel blkwood;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfrgtpwd;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel keyicon;
    private javax.swing.JLabel lockicon;
    private javax.swing.JLabel loginlbl;
    private javax.swing.JLabel ontopblue;
    private javax.swing.JLabel pwdlbl;
    private javax.swing.JLabel shopicon;
    private javax.swing.JLabel themesen;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtlogPswrd;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
