/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnback = new javax.swing.JButton();
        jBtnexit = new javax.swing.JButton();
        jBtnclear = new javax.swing.JButton();
        jBtnsignup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadiobtnmale = new javax.swing.JRadioButton();
        jRadiobtnfemale = new javax.swing.JRadioButton();
        jTextaddress = new javax.swing.JTextField();
        jTextPno = new javax.swing.JTextField();
        jTextusername = new javax.swing.JTextField();
        jTextname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setMinimumSize(new java.awt.Dimension(669, 461));
        setPreferredSize(new java.awt.Dimension(679, 411));
        setResizable(false);
        setSize(new java.awt.Dimension(669, 411));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 390));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 390));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnback.setBackground(new java.awt.Color(0, 0, 0));
        jBtnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnback.setForeground(new java.awt.Color(0, 204, 204));
        jBtnback.setText("Back");
        jBtnback.setBorder(null);
        jBtnback.setMaximumSize(new java.awt.Dimension(81, 25));
        jBtnback.setMinimumSize(new java.awt.Dimension(81, 25));
        jBtnback.setPreferredSize(new java.awt.Dimension(81, 25));
        jBtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 90, 40));

        jBtnexit.setBackground(new java.awt.Color(0, 0, 0));
        jBtnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnexit.setForeground(new java.awt.Color(0, 204, 204));
        jBtnexit.setText("Exit");
        jBtnexit.setBorder(null);
        jBtnexit.setMaximumSize(new java.awt.Dimension(81, 25));
        jBtnexit.setMinimumSize(new java.awt.Dimension(81, 25));
        jBtnexit.setPreferredSize(new java.awt.Dimension(81, 25));
        jPanel1.add(jBtnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, 30));

        jBtnclear.setBackground(new java.awt.Color(0, 0, 0));
        jBtnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnclear.setForeground(new java.awt.Color(0, 204, 204));
        jBtnclear.setText("Clear");
        jBtnclear.setBorder(null);
        jBtnclear.setMaximumSize(new java.awt.Dimension(81, 25));
        jBtnclear.setMinimumSize(new java.awt.Dimension(81, 25));
        jBtnclear.setPreferredSize(new java.awt.Dimension(81, 25));
        jBtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclearActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 90, 30));

        jBtnsignup.setBackground(new java.awt.Color(0, 0, 0));
        jBtnsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnsignup.setForeground(new java.awt.Color(0, 204, 204));
        jBtnsignup.setText("Signup");
        jBtnsignup.setBorder(null);
        jBtnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnsignupActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Phone No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(0, 204, 204));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 170, -1));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 204, 204));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));

        jRadiobtnmale.setBackground(new java.awt.Color(0, 0, 0));
        jRadiobtnmale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadiobtnmale.setForeground(new java.awt.Color(0, 204, 204));
        jRadiobtnmale.setText("Male");
        jPanel1.add(jRadiobtnmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jRadiobtnfemale.setBackground(new java.awt.Color(0, 0, 0));
        jRadiobtnfemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadiobtnfemale.setForeground(new java.awt.Color(0, 204, 204));
        jRadiobtnfemale.setText("Female");
        jPanel1.add(jRadiobtnfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jTextaddress.setBackground(new java.awt.Color(0, 0, 0));
        jTextaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextaddress.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, -1));

        jTextPno.setBackground(new java.awt.Color(0, 0, 0));
        jTextPno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextPno.setForeground(new java.awt.Color(0, 204, 204));
        jTextPno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPnoKeyPressed(evt);
            }
        });
        jPanel1.add(jTextPno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, -1));

        jTextusername.setBackground(new java.awt.Color(0, 0, 0));
        jTextusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextusername.setForeground(new java.awt.Color(0, 204, 204));
        jTextusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextusernameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, -1));

        jTextname.setBackground(new java.awt.Color(0, 0, 0));
        jTextname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextname.setForeground(new java.awt.Color(0, 204, 204));
        jTextname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextnameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("SIGNUP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/blackbg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //VALIDATION
    private void jTextnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnameKeyPressed
      char c = evt.getKeyChar();
if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
{
jTextname.setEditable(true);
}  
else
{
jTextname.setEditable(false);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jTextnameKeyPressed

    private void jTextusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextusernameKeyPressed
            char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
{
jTextusername.setEditable(true);
}else
{
jTextusername.setEditable(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jTextusernameKeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        char c = evt.getKeyChar(); 
        
         if(Character.isLetter(c)||Character.isISOControl(c))
{
jPasswordField1.setEditable(true);
}else
{
jPasswordField1.setEditable(false);
}     
        
// TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
      char c = evt.getKeyChar();
        
         if(Character.isLetter(c)||Character.isISOControl(c))
{
jPasswordField2.setEditable(true);
}else
{
jPasswordField2.setEditable(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jTextPnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPnoKeyPressed

        String phoneno=   jTextPno.getText();
        int length=phoneno.length();
 char c = evt.getKeyChar();
 
 if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
 {
   if(length<11)
        {
 jTextPno.setEditable(true);
 }else
 {
 jTextPno.setEditable(false);
 }
   
 }
 else
 {
 if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()== KeyEvent.VK_DELETE)
 {
 jTextPno.setEditable(true);
 }else
 {
 jTextPno.setEditable(false);
 }
 }
// TODO add your handling code here:
    }//GEN-LAST:event_jTextPnoKeyPressed

    private void jBtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbackActionPerformed
   logininterface log=new logininterface();
log.show();

dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnbackActionPerformed

    private void jBtnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnsignupActionPerformed
     String password=new String(jPasswordField1.getText());
     String confirmpassword =new String(jPasswordField1.getText());
    
if(  !password.equals(confirmpassword))
        {
        JOptionPane.showMessageDialog(this,"password must be same ");
        } else{
         JOptionPane.showMessageDialog(this,"signup successful");
        }
if(jTextusername.getText().equals("")||jTextname.getText().equals("")||jTextaddress.getText().equals("")||
    jTextPno.getText().equals("")||jPasswordField1.getText().equals("")||jPasswordField2.getText().equals("")) 
{
JOptionPane.showMessageDialog(this,"You should enter all Data");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jBtnsignupActionPerformed

    private void jBtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclearActionPerformed
        // TODO add your handling code here:
         jTextusername.setText("");
         jTextname.setText("");
         jTextaddress.setText("");       
         jTextPno.setText("");
         jPasswordField1.setText("");
         jPasswordField2.setText("");
         
    }//GEN-LAST:event_jBtnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnback;
    private javax.swing.JButton jBtnclear;
    private javax.swing.JButton jBtnexit;
    private javax.swing.JButton jBtnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadiobtnfemale;
    private javax.swing.JRadioButton jRadiobtnmale;
    private javax.swing.JTextField jTextPno;
    private javax.swing.JTextField jTextaddress;
    private javax.swing.JTextField jTextname;
    private javax.swing.JTextField jTextusername;
    // End of variables declaration//GEN-END:variables
}
